athena_tester:
  target: athena_tester
  outputs:
    athena_tester:
      type: athena
      s3_staging_dir: "{{ env_var('DBT_ENV_STAGING_DIR') }}"
      region_name: eu-central-1
      database: awsdatacatalog
      schema: tester
      poll_interval: 5
      aws_profile_name: "{{ env_var('AWS_PROFILE') }}"
      work_group: tester
      num_retries: 0
      s3_data_dir: "{{ env_var('DBT_ENV_DATA_DIR') }}"
